name: Test Release

defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
jobs:
  release:
    runs-on: macOS-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      TEST1: ${{ secrets.TEST1 }}
      VERSION: ${{ github.event.inputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and upload Carthage repo artifacts

        run: |
              echo "test3" > test4.txt
              git add .
              git commit -m "test"
              git tag $VERSION
              git push origin master
              git push origin $VERSION
              curl --data '{"tag_name": "'"$VERSION"'","target_commitish": "master","name": "Version '"$VERSION"'","body": "","draft": false,"prerelease": false}' https://api.github.com/repos/mac-ci-jpg/fm2/releases?access_token=$GITHUB_ACCESS_TOKEN | grep '^  "id": ' | sed 's/"id":[ ]*\([^,]*\),/\1/' > /tmp/release-id
              export RELEASE_ID="$(cat /tmp/release-id | sed 's/[ ]*//g')";
              echo "RELEASE_ID=$RELEASE_ID"
              echo "test1" > file.txt
              zip archive file.txt
              curl "https://uploads.github.com/repos/mac-ci-jpg/fm2/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=archive.zip" --header 'Content-Type: application/zip' --upload-file archive.zip -X POST || true
              echo "test2" > file2.txt
              rm archive.zip
              zip archive file2.txt
              curl "https://uploads.github.com/repos/mac-ci-jpg/fm2/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=archive2.zip" --header 'Content-Type: application/zip' --upload-file archive.zip -X POST || true
              echo $TEST1
              echo $TEST1 | base64
              echo $TEST1 | base64 | base64

